### PR TITLE
Update accessor.ts

### PR DESCRIPTION
**Pull request by anrepppp**
Adding a property for the tags-input to accept the raw string from different parts of the application to display in the input box.

### CODE REVIEW

**Comment by Gbuomprisco** [comment]
Hi @anrepppp,

are you sure this will be enough for handling what you need?

**Comment by anrepppp** [comment]
@Gbuomprisco From what i have seen in the old plugin, there in the directive he added 'text' property to the scope object. And that's all i have seen, can you please check it again.
scope: {
            tags: '=ngModel',
            text: '=?',
            templateScope: '=?',
            tagClass: '&',
            onTagAdding: '&',
            onTagAdded: '&',
            onInvalidTag: '&',
            onTagRemoving: '&',
            onTagRemoved: '&',
            onTagClicked: '&',
        },
Here is the link: https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js

**Comment by Gbuomprisco** [comment]
Sorry but there is more to it: the property needs to be bound to the input (which is in tag-input-form)

**Comment by Gbuomprisco** [comment]
This will be taken care of in https://github.com/Gbuomprisco/ng2-tag-input/pull/275

**Comment by anrepppp** [comment]
Thank you, @Gbuomprisco ..!

**Pull request closed without merging**
