### PR TITLE
Fixing onlyFromAutocomplete editable tag in IE

### PR DESCRIPTION
**Pull request by DkArteid**
Fixing problem with Tags being still editable in IE when onlyFromAutocomplete set to true.
Entering the edit state was also making the editable item shows again in the list, even if no change done to the item. 
This problem was only happening in IE

### CODE REVIEW

**Comment by Gbuomprisco** [comment]
Hi @DkArteid,
it would be great if you could comment in the code the reasons of the additions (otherwise, someone wouldn't know why)

**Comment by DkArteid** [comment]
Hey @Gbuomprisco ,

Added some comments, please feel free to correct them or suggest other writing, English is not my first language and sometimes my wordings don't make much sense and/or are full with typos and grammars errors :(

**Comment by Gbuomprisco** [comment]
Hi @DkArteid,
was going to merge but noticed that DS_Store files are checked in, could you remove them?

**Comment by DkArteid** [comment]
Done!

**Pull request merged**
