### PR TITLE
Bugs fixed

### PR DESCRIPTION
**Pull request by Gbuomprisco**

### CODE REVIEW

**Comment by tonysparks** [comment]
Wouldn't we want the `TagModel.value` to be used as the comparison instead of `TagModel.display` as the display is just for display purposes?  (Unless my understanding is incorrect of the functionality -- I thought display could include HTML code)

**Comment by Gbuomprisco** [comment]
@tonysparks it's what I thought initially - but the problem I saw is we know the value of the items pre-entered, though we can only assume the value of items entered by the user as its display value. So it would be possible that duplicate items could be entered in that case:

```
initialModel {value: 0, display: 'Angular''}
user entered tah {value: 'Angular', display: 'Angular''} // dupe, but OK
```

If we assume the display value as its value, we don't get the issue. On the other hand, it is also not possible to add duplicate items if the dev wanted to (which would be a case I'd like to allow).

Do you have a better idea?

**Comment by tonysparks** [comment]
Given that there are two ways to create a TagModel:

1. Drop down values (i.e., `AutocompleteItemModel`; which has a `value` and `display` too)
2. User entered values

Would this work:

* For dropdown picked items:
```
tagModel.value = autocompleteModel.value
tagModel.display = autocompleteModel.value
```
* For user entered in items:
```
tagModel.value = inputForm.value
tagModel.display = inputForm.value
```

This would allow duplicate checks based on the `tagModel.value` and would be consistent for both drop down values and user entered values.

**Comment by Gbuomprisco** [comment]
Hi @tonysparks, thanks for writing this.

That makes sense, but I believe the issue with `value` still stands in the sense that 2 tags may have the same display but a different value when they are provided by the user, and when instead they have been provided as a model.

The only use-case I see for `value` is its use with `trackBy` (which is currently disabled)

So let us say I, as a dev, add the following model:
```
model = [{display: 'React', value: '1', {display: 'Angular': value: '2'}];
```

And as a user, I add the tag: 'React':

Here, I can compare with `React` with the display value of `1`, but not with `1`.

**Pull request merged**
